apiVersion: v1
kind: ConfigMap
metadata:
  name: startup-script-cpu
data:
  startup-script.sh: |
    #!/bin/bash
    apt update
    apt install curl -y
    curl -fsSL https://code-server.dev/install.sh | sh
    code-server --bind-addr 0.0.0.0:8080
---
apiVersion: v1
kind: Service
metadata:
  name: codeserver
spec:
  selector:
    app: codeserver
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver
spec:
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      containers:
        - name: codeserver
          image: ubuntu
          command: ["/script/startup-script.sh"]
          volumeMounts:
            - name: script-volume
              mountPath: /script
          resources:
            limits:
              memory: "16Gi"
              cpu: "8"
          ports:
            - containerPort: 8080
      volumes:
        - name: script-volume
          configMap:
            name: startup-script-cpu
            defaultMode: 0744
