apiVersion: v1
kind: ConfigMap
metadata:
  name: startup-script
data:
  startup-script.sh: |
    #!/bin/bash
    apt update
    apt install curl -y
    curl -fsSL https://code-server.dev/install.sh | sh
    code-server --auth none --bind-addr 0.0.0.0:8080
---
apiVersion: v1
kind: Service
metadata:
  name: cuda-code
spec:
  selector:
    app: cuda-code
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuda-code
spec:
  selector:
    matchLabels:
      app: cuda-code
  template:
    metadata:
      labels:
        app: cuda-code
    spec:
      containers:
        - name: cuda-code
          image: nvcr.io/nvidia/cuda:12.2.2-devel-ubuntu22.04
          command: ["/script/startup-script.sh"]
          volumeMounts:
            - name: script-volume
              mountPath: /script
          resources:
            limits:
              memory: "16Gi"
              cpu: "8"
              nvidia.com/gpu: "1"
          ports:
            - containerPort: 8080
      volumes:
        - name: script-volume
          configMap:
            name: startup-script
            defaultMode: 0744
